name: ShellCheck

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: sudo apt-get install -y shellcheck
    - name: shellcheck
      run: shellcheck --exclude=SC2154,SC2034 ./*/*.sh
